[[provider_endpoints]]
name = "astroport_neutron"
url_set = "api_neutron"

[[provider_endpoints]]
name = "fin"
url_set = "fin"

[[provider_endpoints]]
name = "finv2"
url_set = "api_kujira"

[[provider_endpoints]]
name = "osmosisv2"
url_set = "api_osmosis"

[[provider_endpoints]]
name = "uniswapv3"
url_set = "rpc_ethereum"

[contract_addresses.astroport_neutron]
NTRNATOM = "neutron1e22zh5p8meddxjclevuhjmfj69jxfsa8uu3jvht72rv9d8lkhves6t8veq"
STATOMATOM = "neutron1l7ny0rckx9rks2p2aq94wd74sehjczym6n9y4yax8lcy9s39uans4uga62"

[contract_addresses.camelotv3]
KUJIWETH = "0x22427d20480de289795ca29c3adddb57a568e285"
WETHGMX = "0xC99be44383BC8d82357F5A1D9ae9976EE9d75bee"
WETHUSDC = "0x521aa84ab3fcc4c05cABaC24Dc3682339887B126"

[contract_addresses.finv2]
AMPKUJIKUJI = "kujira1lse59wt7a5yksdd08mennt299katjkfzdhmh8hvck8ln08jktcmsxrnh8s"
KUJIUSDC = "kujira14hj2tavq8fpesdwxxcu44rty3hh90vhujrvcmstl4zr3txmfvw9sl4e867"
KUJIUSK = "kujira193dzcmy7lwuj4eda3zpwwt9ejal00xva0vawcvhgsyyp5cfh6jyq66wfrf"
MNTAUSDC = "kujira1ws9w7wl68prspv3rut3plv8249rm0ea0kk335swye3sl2slld4lqdmc0lv"
NSTKUSK = "kujira1ggtmfuktfcf6plhtdejyyqn5de5uge3tef0jv64ru68h2ctuvyqs3355mn"
QCKUJIKUJI = "kujira14wsrem89304kpkl6d0j58dl6479eekwt047ccs0qzv9f60w80wzs8rjq4j"
QCMNTAMNTA = "kujira1ujsr2ge7dr723kse7thjv2rm3k7dkmjaxqzdh8qkcnx5gqz57jsqxy4ker"
SOMMMNTA = "kujira1nx5lqc2j4w0ak5dxevj82lar5kunxwj5yamr39xqfazmkksx4f2sksf0hz"
STARSMNTA = "kujira1hsdzhyvuc2z3f8d3yae84uk62d69vk68vxgudkun7gccz6hvrvfq0vx6fd"
STATOMMNTA = "kujira1l2x5c2fjjnw9uhrfhtme9snw3tzs4jt8cm0q2ysqssx6zskxatesjm7w7f"
USDCUSK = "kujira1rwx6w02alc4kaz7xpyg3rlxpjl4g63x5jq292mkxgg65zqpn5llq202vh5"
WHALEMNTA = "kujira1865zmuchjd0g0xr2q5n6hm747s8xju5k8h6mympk4vmqefkuy3hqc66tcw"
WINKUSK = "kujira1qxtd87qus6uzvqs4jv9r0j9ccd4yla42s6qag7y8fp7hhv68nzas6hqxgw"
STATOMATOM = "kujira158zzjcvkz7r3j5hueurcw22qrjerqw4dtrzlalztr7whjykjwvrsrahdnq"

[contract_addresses.osmosisv2]
JUNOOSMO = "1097"
MNTAOSMO = "1215"
SOMMOSMO = "627"
STARSOSMO = "604"
STATOMATOM = "1136"
STOSMOOSMO = "833"
WHALEOSMO = "1318"
NTRNUSDC = "1324"

[contract_addresses.pancakev3_bsc]
ETHRIO = "0x043681828303cdf9398f0768bf1da99feebf7ee8"

[contract_addresses.uniswapv3]
RLBWETH = "0x510100d5143e011db24e2aa38abe85d73d5b2177"
USDCWETH = "0x88e6a0c2ddd26feeb64f039a2c41296fcb3f5640"
WETHRIO = "0x5b7e3e37a1aa6369386e5939053779abd3597508"
WSTETHWETH = "0x109830a1AAaD605BbF02a9dFA7B0B92EC2FB7dAa"