[[currency_pairs]]
base = "AKT"
quote = "USD"
providers = ["crypto", "kraken"]

[[currency_pairs]]
base = "AKT"
quote = "USDT"
providers = ["gate", "huobi", "kucoin"]

[[currency_pairs]]
base = "AMPKUJI"
quote = "KUJI"
providers = ["finv2"]
derivative = "twap"
derivative_period = "30m"

[[currency_pairs]]
base = "ARB"
quote = "USD"
providers = ["bitfinex", "coinbase", "crypto", "kraken"]

[[currency_pairs]]
base = "ARB"
quote = "USDT"
providers = [
    "binance",
    "bitget",
    "bybit",
    "gate",
    "hitbtc",
    "huobi",
    "kucoin",
    "lbank",
    "mexc",
    "okx",
    "phemex",
    "xt",
]

[[currency_pairs]]
base = "ATOM"
quote = "USD"
providers = ["coinbase", "kraken"]

[[currency_pairs]]
base = "ATOM"
quote = "USDT"
providers = [
    "binance",
    "bitget",
    "bybit",
    "crypto",
    "gate",
    "hitbtc",
    "huobi",
    "kucoin",
    "lbank",
    "mexc",
    "okx",
    "phemex",
    "poloniex",
    "xt",
]

[[currency_pairs]]
base = "AVAX"
quote = "USD"
providers = ["bitfinex", "coinbase", "kraken"]

[[currency_pairs]]
base = "AVAX"
quote = "USDT"
providers = [
    "binance",
    "bitget",
    "bybit",
    "crypto",
    "gate",
    "hitbtc",
    "huobi",
    "kucoin",
    "lbank",
    "mexc",
    "okx",
    "phemex",
    "poloniex",
    "xt",
]

[[currency_pairs]]
base = "AXL"
quote = "USD"
providers = ["coinbase", "crypto", "kraken"]

[[currency_pairs]]
base = "AXL"
quote = "USDT"
providers = ["bitget", "bybit", "gate", "huobi", "kucoin", "mexc"]

[[currency_pairs]]
base = "AXL"
quote = "MNTA"
providers = ["fin"]
derivative = "twap"
derivative_period = "30m"

[[currency_pairs]]
base = "BAND"
quote = "USDT"
providers = [
    "binance",
    "bitget",
    "crypto",
    "gate",
    "hitbtc",
    "huobi",
    "kucoin",
    "okx",
    "phemex",
]

[[currency_pairs]]
base = "BNB"
quote = "USDT"
providers = [
    "binance",
    "bitget",
    "bybit",
    "gate",
    "hitbtc",
    "huobi",
    "kucoin",
    "lbank",
    "mexc",
    "okx",
    "phemex",
    "poloniex",
    "xt",
]

[[currency_pairs]]
base = "BTC"
quote = "USD"
providers = ["bitfinex", "coinbase"]

[[currency_pairs]]
base = "BTC"
quote = "USDT"
providers = [
    "binance",
    "bitget",
    "bybit",
    "crypto",
    "gate",
    "hitbtc",
    "huobi",
    "kucoin",
    "lbank",
    "mexc",
    "okx",
    "phemex",
    "poloniex",
    "xt",
]

[[currency_pairs]]
base = "CRO"
quote = "USDT"
providers = ["bitget", "crypto", "gate", "kucoin", "lbank", "mexc", "okx", "xt"]

[[currency_pairs]]
base = "DOT"
quote = "USD"
providers = ["bitfinex", "coinbase", "crypto", "kraken"]

[[currency_pairs]]
base = "DOT"
quote = "USDT"
providers = [
    "binance",
    "bitget",
    "bybit",
    "gate",
    "hitbtc",
    "huobi",
    "kucoin",
    "lbank",
    "mexc",
    "okx",
    "phemex",
    "poloniex",
    "xt",
]

[[currency_pairs]]
base = "ETH"
quote = "USD"
providers = ["bitfinex", "coinbase", "crypto"]

[[currency_pairs]]
base = "ETH"
quote = "USDT"
providers = [
    "binance",
    "bitget",
    "bybit",
    "gate",
    "hitbtc",
    "huobi",
    "kraken",
    "kucoin",
    "lbank",
    "mexc",
    "okx",
    "phemex",
    "poloniex",
    "xt",
]

[[currency_pairs]]
base = "FET"
quote = "USD"
providers = ["bitfinex", "coinbase", "kraken"]

[[currency_pairs]]
base = "FET"
quote = "USDT"
providers = [
    "binance",
    "bitget",
    "crypto",
    "gate",
    "huobi",
    "kucoin",
    "lbank",
    "mexc",
    "phemex",
]

[[currency_pairs]]
base = "FTM"
quote = "USD"
providers = ["bitfinex", "kraken"]

[[currency_pairs]]
base = "FTM"
quote = "USDT"
providers = [
    "binance",
    "bitget",
    "bybit",
    "crypto",
    "gate",
    "hitbtc",
    "huobi",
    "kucoin",
    "lbank",
    "mexc",
    "okx",
    "phemex",
]

[[currency_pairs]]
base = "GLMR"
quote = "USDT"
providers = [
    "binance",
    "bitget",
    "bybit",
    "crypto",
    "gate",
    "huobi",
    "kucoin",
    "lbank",
    "mexc",
    "okx",
    "xt",
]

[[currency_pairs]]
base = "HNT"
quote = "USD"
providers = ["coinbase", "crypto"]

[[currency_pairs]]
base = "HNT"
quote = "USDT"
providers = ["bitget", "bitmart", "bybit", "gate", "kucoin"]

[[currency_pairs]]
base = "INJ"
quote = "USD"
providers = ["coinbase", "kraken"]

[[currency_pairs]]
base = "INJ"
quote = "USDT"
providers = [
    "binance",
    "bitget",
    "bybit",
    "crypto",
    "gate",
    "hitbtc",
    "huobi",
    "kucoin",
    "lbank",
    "mexc",
    "phemex",
]

[[currency_pairs]]
base = "JUNO"
quote = "USD"
providers = ["kraken"]

[[currency_pairs]]
base = "JUNO"
quote = "USDT"
providers = ["mexc"]

[[currency_pairs]]
base = "JUNO"
quote = "OSMO"
providers = ["osmosisv2"]

[[currency_pairs]]
base = "KAVA"
quote = "USD"
providers = ["coinbase", "kraken"]

[[currency_pairs]]
base = "KAVA"
quote = "USDT"
providers = [
    "binance",
    "bitget",
    "crypto",
    "gate",
    "huobi",
    "kucoin",
    "lbank",
    "mexc",
    "xt",
]

[[currency_pairs]]
base = "KUJI"
quote = "USDT"
providers = ["mexc"]
derivative = "twap"
derivative_period = "30m"

[[currency_pairs]]
base = "KUJI"
quote = "USK"
providers = ["fin"]
derivative = "twap"
derivative_period = "30m"

[[currency_pairs]]
base = "KUJI"
quote = "WETH"
providers = ["camelotv3"]
derivative = "twap"
derivative_period = "30m"

[[currency_pairs]]
base = "LINK"
quote = "USD"
providers = ["coinbase", "crypto", "kraken"]

[[currency_pairs]]
base = "LINK"
quote = "USDT"
providers = [
    "binance",
    "bitget",
    "bybit",
    "gate",
    "huobi",
    "lbank",
    "mexc",
    "okx",
    "phemex",
    "xt",
]

[[currency_pairs]]
base = "LUNA"
quote = "USD"
providers = ["kraken"]

[[currency_pairs]]
base = "LUNA"
quote = "USDT"
providers = [
    "binance",
    "bitget",
    "bybit",
    "gate",
    "hitbtc",
    "huobi",
    "kucoin",
    "lbank",
    "mexc",
    "okx",
    "phemex",
    "xt",
]

[[currency_pairs]]
base = "LUNC"
quote = "USD"
providers = ["crypto", "kraken"]

[[currency_pairs]]
base = "LUNC"
quote = "USDT"
providers = [
    "binance",
    "bitget",
    "bybit",
    "gate",
    "hitbtc",
    "huobi",
    "kucoin",
    "lbank",
    "mexc",
    "okx",
    "phemex",
    "xt",
]

[[currency_pairs]]
base = "MATIC"
quote = "USD"
providers = ["bitfinex", "coinbase", "crypto", "kraken"]

[[currency_pairs]]
base = "MATIC"
quote = "USDT"
providers = [
    "binance",
    "bitget",
    "bybit",
    "gate",
    "hitbtc",
    "huobi",
    "kucoin",
    "lbank",
    "mexc",
    "okx",
    "phemex",
    "poloniex",
    "xt",
]

[[currency_pairs]]
base = "MNTA"
quote = "USDC"
providers = ["finv2"]
derivative = "twap"
derivative_period = "30m"

[[currency_pairs]]
base = "NTRN"
quote = "ATOM"
providers = ["astroport_neutron"]
derivative = "twap"
derivative_period = "30m"

[[currency_pairs]]
base = "NTRN"
quote = "USDC"
providers = ["osmosisv2"]
derivative = "twap"
derivative_period = "30m"

[[currency_pairs]]
base = "NTRN"
quote = "USDT"
providers = ["binance", "gate", "kucoin", "mexc"]

[[currency_pairs]]
base = "OSMO"
quote = "USD"
providers = ["coinbase", "crypto"]

[[currency_pairs]]
base = "OSMO"
quote = "USDT"
providers = ["binance", "bitget", "gate", "huobi", "kucoin", "lbank", "mexc"]

[[currency_pairs]]
base = "PAXG"
quote = "USD"
providers = ["kraken"]

[[currency_pairs]]
base = "PAXG"
quote = "USDT"
providers = [
    "binance",
    "bitget",
    "bybit",
    "crypto",
    "kucoin",
    "lbank",
    "mexc",
    "phemex",
]

[[currency_pairs]]
base = "RLB"
quote = "WETH"
providers = ["uniswapv3"]
derivative = "twap"
derivative_period = "30m"

[[currency_pairs]]
base = "SCRT"
quote = "USD"
providers = ["kraken"]

[[currency_pairs]]
base = "SCRT"
quote = "USDT"
providers = ["binance", "bybit", "gate", "huobi", "kucoin", "lbank", "mexc"]

[[currency_pairs]]
base = "SOMM"
quote = "OSMO"
providers = ["osmosisv2"]
derivative = "twap"
derivative_period = "30m"

[[currency_pairs]]
base = "SOL"
quote = "USD"
providers = ["coinbase", "kraken"]

[[currency_pairs]]
base = "SOL"
quote = "USDT"
providers = [
    "binance",
    "bitget",
    "bybit",
    "gate",
    "huobi",
    "kucoin",
    "okx",
    "xt",
]

[[currency_pairs]]
base = "STARS"
quote = "OSMO"
providers = ["osmosisv2"]
derivative = "twap"
derivative_period = "30m

[[currency_pairs]]
base = "STATOM"
quote = "ATOM"
providers = ["astroport_neutron", "finv2", "osmosisv2"]
derivative = "twap"
derivative_period = "30m"

[[currency_pairs]]
base = "STOSMO"
quote = "OSMO"
providers = ["osmosisv2"]
derivative = "twap"
derivative_period = "30m"

[[currency_pairs]]
base = "UNI"
quote = "USD"
providers = ["coinbase", "crypto", "kraken"]

[[currency_pairs]]
base = "UNI"
quote = "USDT"
providers = [
    "binance",
    "bitget",
    "bybit",
    "gate",
    "huobi",
    "lbank",
    "okx",
    "phemex",
]

[[currency_pairs]]
base = "USDC"
quote = "USD"
providers = ["kraken"]

[[currency_pairs]]
base = "USDC"
quote = "USDT"
providers = [
    "binance",
    "bitget",
    "bybit",
    "gate",
    "huobi",
    "kucoin",
    "lbank",
    "mexc",
    "okx",
    "phemex",
    "xt",
]

[[currency_pairs]]
base = "USDT"
quote = "USD"
providers = ["binanceus", "coinbase", "crypto", "gate", "kraken"]

[[currency_pairs]]
base = "USK"
quote = "USDC"
providers = ["finv2"]
derivative = "twap"
derivative_period = "30m"

[[currency_pairs]]
base = "RIO"
quote = "USDT"
providers = ["mexc", "okx"]

[[currency_pairs]]
base = "RIO"
quote = "ETH"
providers = ["pancakev3_bsc"]
derivative = "twap"
derivative_period = "30m"

[[currency_pairs]]
base = "RIO"
quote = "USK"
providers = ["fin"]
derivative = "twap"
derivative_period = "30m"

[[currency_pairs]]
base = "NSTK"
quote = "USK"
providers = ["finv2"]
derivative = "twap"
derivative_period = "30m"

[[currency_pairs]]
base = "QCKUJI"
quote = "KUJI"
providers = ["finv2"]
derivative = "twap"
derivative_period = "30m"

[[currency_pairs]]
base = "QCMNTA"
quote = "MNTA"
providers = ["finv2"]
derivative = "twap"
derivative_period = "30m"

[[currency_pairs]]
base = "WBTC"
quote = "BTC"
providers = ["binance", "coinbase", "kucoin", "okx"]

[[currency_pairs]]
base = "WBTC"
quote = "USDT"
providers = [
    "bitget",
    "bybit",
    "crypto",
    "gate",
    "hitbtc",
    "mexc",
    "phemex",
    "poloniex",
]

[[currency_pairs]]
base = "WHALE"
quote = "USDT"
providers = ["mexc"]
derivative = "twap"
derivative_period = "30m"

[[currency_pairs]]
base = "WHALE"
quote = "OSMO"
providers = ["osmosisv2"]
derivative = "twap"
derivative_period = "30m"

[[currency_pairs]]
base = "WHALE"
quote = "MNTA"
providers = ["fin"]
derivative = "twap"
derivative_period = "30m"

[[currency_pairs]]
base = "WINK"
quote = "USK"
providers = ["finv2"]
derivative = "twap"
derivative_period = "30m"

[[currency_pairs]]
base = "WSTETH"
quote = "WETH"
providers = ["uniswapv3"]
derivative = "twap"
derivative_period = "30m"

[[currency_pairs]]
base = "WETH"
quote = "USDC"
providers = ["uniswapv3"]

[[currency_pairs]]
base = "SHD"
quote = "MNTA"
providers = ["finv2", "shade"]
derivative = "twap"
derivative_period = "30m"