[[provider_min_overrides]]
denoms = [
    "AMPKUJI",
    "JUNO",
    "MNTA",
    "NSTK",
    "NTRN",
    "QCKUJI",
    "QCMNTA",
    "RLB",
    "SHD",
    "SOMM",
    "STARS",
    "STATOM",
    "STKATOM",
    "STOSMO",
    "USK",
    "WETH",
    "WHALE",
    "WINK",
    "WSTETH",
]
providers = 1

[[provider_min_overrides]]
denoms = ["KUJI", "RIO"]
providers = 2
