[[provider_min_overrides]]
denoms = ["KUJI", "QCKUJI", "QCMNTA", "NSTK"]
providers = 1

[[provider_min_overrides]]
denoms = ["WHALE", "STARS", "SOMM", "STATOM", "STOSMO", "MNTA", "WINK", "USK", "WETH", "WSTETH"]
providers = 1

[[provider_min_overrides]]
denoms = ["RLB"]
providers = 1

[[provider_min_overrides]]
denoms = ["NTRN"]
providers = 1